### ISSUE TITLE
Recognize @-character

### ISSUE THREAD

**Issue by frankred** [antimatter15/ocrad.js#10]
Amazing project!

I have problems with the recognition of the ```@```. Is that even possible?

Here is an example image: http://jlanchat.mynotiz.de/author.gif  or http://i.imgur.com/Qao5YSS.png

**Comment by antimatter15** [comment]
I'm currently working on a Convnet.JS based OCR library. It doesn't work yet, but it'll be able to recognize @ signs. https://github.com/naptha/ocracy
