### ISSUE TITLE
Unable to scan numbers

### ISSUE THREAD

**Issue by konycert** [antimatter15/ocrad.js#13]
Dear antimatter15,

  when scanning numbers, such as the following image
http://lancelotlam.com/numbertest/numbers.png

 ocrad.js  only detect 

___ - ______'__'__'r'
_ _ __
___-____________
_ ___7 __' __o,__o,7o,
__'T-| __T__T__T_O,
. E_ _ _ _ _
- ___-____-____-______-____
 
most of the numbers were scanned as _

i have found the following enums in common.cc 

const char * const charset_name[charsets] =
  { "ascii", "iso-8859-9", "iso-8859-15" };

and 

const F_entry F_table[] =
  {
  { "none",         Filter::none },
  { "letters",      Filter::letters },
  { "letters_only", Filter::letters_only },
  { "numbers",      Filter::numbers },
  { "numbers_only", Filter::numbers_only },
  { 0, Filter::none }
  };

but how to apply that on javascript side?

Thanks and regards

**Comment by antimatter15** [comment]
I've updated it to Ocrad 0.24 and built the javascript bindings for applying filters and other things. Look at `examples/browser/numbers.html` for how to restrict it to numeric recognition.
