### ISSUE TITLE
not identify Chinese

### ISSUE THREAD

**Issue by hijoys** [antimatter15/ocrad.js#21]
the Ocrad.js  was unable to properly identify Chinese.

**Comment by cades** [comment]
feature request +1

the [Ocrad documentation](http://www.gnu.org/software/ocrad/manual/ocrad_manual.html#Character-sets) page said it support charset, could we expose this option to ocrad.js API?

**Comment by cades** [comment]
just play with ocrad command, find it only support charset: ascii  iso-8859-9  iso-8859-15
which means chinese is not supported... what a pity :(

**Comment by antimatter15** [comment]
Yeah, Ocrad doesn't support anything other than the basic latin character set. However, I'm currently working on a port of Tesseract (I'm figuring out how to make it smaller and faster right now)— and it should be possible to get Chinese to work with that.

**Comment by pedrovieira7** [comment]
@antimatter15 any updates on that port with chinese characters?

**Comment by antimatter15** [comment]
It'll be launching within a week, keep tuned.

**Comment by pedrovieira7** [comment]
@antimatter15 awesome! can't wait

**Comment by wxyyxc1992** [comment]
can i use it for chinese now?

**Comment by antimatter15** [comment]
yyou can check out http://tesseract.projectnaptha.com/
