### ISSUE TITLE
Error in the demo

### ISSUE THREAD

**Issue by benjick** [antimatter15/ocrad.js#23]
![From the demo](http://i.imgur.com/OBD3UoQ.png)

Is this supposed to happen or is it something with my browser?

Chrome 43 on Windows 10

**Comment by antimatter15** [comment]
Yeah recognition accuracy isn't super fantastically great, this is just how it works.

**Comment by benjick** [comment]
I see. Thank you. Do you have any other recommendation regarding ocr
software?
